<a href="https://colab.research.google.com/github/chandu01432/Upskill/blob/main/Pandas%20-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
ser = pd.Series([20,30,42,50], name = 'Age')
ser

0    20
1    30
2    42
3    50
Name: Age, dtype: int64

In [ ]:
ser = pd.Series([20,30,42,50], name = 'Age', index = ['a','b', 'c', 'd'])
ser

a    20
b    30
c    42
d    50
Name: Age, dtype: int64

In [ ]:
d1 = {'One': 1, 'Two': 2, 'Three': 3}

ds = pd.Series(d1,name = 'Age')
ds

One      1
Two      2
Three    3
Name: Age, dtype: int64

In [ ]:
lst = [['Anirban',30],['Ayush',28], ['Lavanya',29]]
df = pd.DataFrame(lst, columns = ['Name_l','Age_l'])
df

    Name_l  Age_l
0  Anirban     30
1    Ayush     28
2  Lavanya     29

In [ ]:
d1 = {'Names': ['Anirban','Ayush'], 'Age':[30,28]}

ds = pd.DataFrame(d1)
ds

     Names  Age
0  Anirban   30
1    Ayush   28

In [ ]:
ds

     Names  Age
0  Anirban   30
1    Ayush   28

In [ ]:
df

    Name_l  Age_l
0  Anirban     30
1    Ayush     28
2  Lavanya     29

In [ ]:
df.join(ds)

    Name_l  Age_l    Names   Age
0  Anirban     30  Anirban  30.0
1    Ayush     28    Ayush  28.0
2  Lavanya     29      NaN   NaN

In [ ]:
ds.join(df)

     Names  Age   Name_l  Age_l
0  Anirban   30  Anirban     30
1    Ayush   28    Ayush     28

In [ ]:
d1l = {'Alpha_left':['a','b','c','d'],
       'Number':[1,2,6,5],
       'Alphanumeric_left':['a','b','c','d']
       }
df_l = pd.DataFrame(d1l)
df_l

  Alpha_left  Number Alphanumeric_left
0          a       1                 a
1          b       2                 b
2          c       6                 c
3          d       5                 d

In [ ]:
d1r = {'Alpha_right':['a','b','c','d'],
       'Number':[5,6,7,8],
       'Alphanumeric_right':['e5','f6','g7','h8']
       }
df_r = pd.DataFrame(d1r)
df_r

  Alpha_right  Number Alphanumeric_right
0           a       5                 e5
1           b       6                 f6
2           c       7                 g7
3           d       8                 h8

In [ ]:
df_inner = pd.merge(df_l, df_r, on='Number', how = 'inner')
df_inner

  Alpha_left  Number Alphanumeric_left Alpha_right Alphanumeric_right
0          c       6                 c           b                 f6
1          d       5                 d           a                 e5

In [ ]:
df_left = pd.merge(df_l, df_r, on='Number', how = 'left')
df_left

  Alpha_left  Number Alphanumeric_left Alpha_right Alphanumeric_right
0          a       1                 a         NaN                NaN
1          b       2                 b         NaN                NaN
2          c       6                 c           b                 f6
3          d       5                 d           a                 e5

In [ ]:
df_right = pd.merge(df_l, df_r, on='Number', how = 'right')
df_right

  Alpha_left  Number Alphanumeric_left Alpha_right Alphanumeric_right
0          d       5                 d           a                 e5
1          c       6                 c           b                 f6
2        NaN       7               NaN           c                 g7
3        NaN       8               NaN           d                 h8

In [ ]:
df_outer = pd.merge(df_l, df_r, on='Number', how = 'outer')
df_outer

  Alpha_left  Number Alphanumeric_left Alpha_right Alphanumeric_right
0          a       1                 a         NaN                NaN
1          b       2                 b         NaN                NaN
2          d       5                 d           a                 e5
3          c       6                 c           b                 f6
4        NaN       7               NaN           c                 g7
5        NaN       8               NaN           d                 h8