<a href="https://colab.research.google.com/github/chandu01432/Upskill/blob/main/Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('mtcars2.csv')
df

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
df.head()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [ ]:
df.tail()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   S.No        32 non-null     int64
 1   Unnamed: 1  32 non-null     object
 2   mpg         32 non-null     float64
 3   cyl         32 non-null     int64
 4   disp        32 non-null     float64
 5   hp          32 non-null     int64
 6   drat        32 non-null     float64
 7   wt          32 non-null     float64
 8   qsec        29 non-null     float64
 9   vs          32 non-null     int64
 10  am          32 non-null     int64
 11  gear        32 non-null     int64
 12  carb        32 non-null     int64
dtypes: float64(5), int64(7), object(1)
memory usage: 3.4+ KB

In [ ]:
df.isnull().sum()

S.No          0
Unnamed: 1    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          0
vs            0
am            0
gear          0
carb          0
dtype: int64

In [ ]:
df.describe()

,S.No,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.0000
mean,16.500000,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.674828,0.437500,0.406250,3.687500,2.8125
std,9.380832,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.780394,0.504016,0.498991,0.737804,1.6152
min,1.000000,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,8.750000,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.870000,0.000000,0.000000,3.000000,2.0000
50%,16.500000,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.420000,0.000000,0.000000,4.000000,2.0000
75%,24.250000,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.600000,1.000000,1.000000,4.000000,4.0000
max,32.000000,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [ ]:
df.qsec.mean()

np.float64(17.6748275862069)

In [ ]:
df.qsec = df.qsec.fillna(df.qsec.mean())
df

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.460000,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.020000,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.610000,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.440000,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.020000,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,17.674828,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.840000,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.000000,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.900000,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.300000,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.900000,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.400000,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.600000,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.000000,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.980000,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.820000,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.420000,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,17.674828,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.520000,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.900000,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.010000,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.870000,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.300000,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.410000,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.050000,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,17.674828,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.700000,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.900000,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.500000,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.500000,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.600000,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.600000,1,1,4,2

In [ ]:
df = df.drop(columns = ['S.No'])
df

,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.460000,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.020000,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.610000,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.440000,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.020000,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,17.674828,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.840000,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.000000,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.900000,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.300000,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.900000,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.400000,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.600000,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.000000,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.980000,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.820000,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.420000,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,17.674828,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.520000,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.900000,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.010000,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.870000,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.300000,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.410000,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.050000,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,17.674828,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.700000,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.900000,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.500000,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.500000,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.600000,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.600000,1,1,4,2

In [ ]:
df = df.rename(columns = {'Unnamed: 1':'Cars'})
df

,Cars,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.460000,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.020000,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.610000,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.440000,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.020000,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,17.674828,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.840000,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.000000,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.900000,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.300000,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.900000,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.400000,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.600000,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.000000,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.980000,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.820000,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.420000,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,17.674828,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.520000,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.900000,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.010000,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.870000,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.300000,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.410000,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.050000,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,17.674828,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.700000,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.900000,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.500000,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.500000,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.600000,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.600000,1,1,4,2

In [ ]:
df[4:20][['mpg','Cars']]

     mpg                 Cars
4   18.7    Hornet Sportabout
5   18.1              Valiant
6   14.3           Duster 360
7   24.4            Merc 240D
8   22.8             Merc 230
9   19.2             Merc 280
10  17.8            Merc 280C
11  16.4           Merc 450SE
12  17.3           Merc 450SL
13  15.2          Merc 450SLC
14  10.4   Cadillac Fleetwood
15  10.4  Lincoln Continental
16  14.7    Chrysler Imperial
17  32.4             Fiat 128
18  30.4          Honda Civic
19  33.9       Toyota Corolla

In [ ]:
df.iloc[4:20, 2:5] #stands for integer location

    cyl   disp   hp
4     8  360.0  175
5     6  225.0  105
6     8  360.0  245
7     4  146.7   62
8     4  140.8   95
9     6  167.6  123
10    6  167.6  123
11    8  275.8  180
12    8  275.8  180
13    8  275.8  180
14    8  472.0  205
15    8  460.0  215
16    8  440.0  230
17    4   78.7   66
18    4   75.7   52
19    4   71.1   65

In [ ]:
df.loc[4:20, 'Cars':'wt']

                   Cars   mpg  cyl   disp   hp  drat     wt
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440
5               Valiant  18.1    6  225.0  105  2.76  3.460
6            Duster 360  14.3    8  360.0  245  3.21  3.570
7             Merc 240D  24.4    4  146.7   62  3.69  3.190
8              Merc 230  22.8    4  140.8   95  3.92  3.150
9              Merc 280  19.2    6  167.6  123  3.92  3.440
10            Merc 280C  17.8    6  167.6  123  3.92  3.440
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345
17             Fiat 128  32.4    4   78.7   66  4.08  2.200
18          Honda Civic  30.4    4   75.7   52  4.93  1.615
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465

In [ ]:
import numpy as np
lst = np.arange(0,32,1)

In [ ]:
df['new column'] = lst

In [ ]:
df.sort_values(by = 'cyl', ascending = False)

,Cars,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new column
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.420000,0,0,3,4,16
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.600000,0,1,5,8,30
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.020000,0,0,3,2,4
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.500000,0,1,5,4,28
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.840000,0,0,3,4,6
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.050000,0,0,3,2,24
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.410000,0,0,3,4,23
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.300000,0,0,3,2,22
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.870000,0,0,3,2,21
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.400000,0,0,3,3,11
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.600000,0,0,3,3,12
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.000000,0,0,3,3,13
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.980000,0,0,3,4,14
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.820000,0,0,3,4,15
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.020000,0,1,4,4,1
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.500000,0,1,5,6,29
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.460000,0,1,4,4,0
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.900000,1,0,4,4,10
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.300000,1,0,4,4,9
5,Valiant,18.1,6,225.0,105,2.76,3.460,17.674828,1,0,3,1,5
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.440000,1,0,3,1,3
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,17.674828,1,1,4,1,17
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.520000,1,1,4,2,18
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.900000,1,1,4,1,19
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.010000,1,0,3,1,20
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.900000,1,0,4,2,8
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.000000,1,0,4,2,7
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,17.674828,1,1,4,1,25
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.700000,0,1,5,2,26
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.900000,1,1,5,2,27
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.610000,1,1,4,1,2
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.600000,1,1,4,2,31

In [ ]:
df[(df.cyl>4) & (df.am==1)]

,Cars,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new column
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,0
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4,28
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6,29
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8,30

In [ ]:
df[df['Cars'].isin(['Mazda RX4', 'Ferrari Dino'])]

,Cars,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new column
0,Mazda RX4,21.0,6,160.0,110,3.90,2.62,16.46,0,1,4,4,0
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.77,15.50,0,1,5,6,29

In [ ]:
df[df['Cars'].str.contains('Mazda')]

,Cars,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new column
0,Mazda RX4,21.0,6,160.0,110,3.9,2.620,16.46,0,1,4,4,0
1,Mazda RX4 Wag,21.0,6,160.0,110,3.9,2.875,17.02,0,1,4,4,1

In [ ]:
df['Length Car Names'] = df.Cars.apply(len)

df

,Cars,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new column,Length Car Names
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.460000,0,1,4,4,0,9
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.020000,0,1,4,4,1,13
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.610000,1,1,4,1,2,10
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.440000,1,0,3,1,3,14
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.020000,0,0,3,2,4,17
5,Valiant,18.1,6,225.0,105,2.76,3.460,17.674828,1,0,3,1,5,7
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.840000,0,0,3,4,6,10
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.000000,1,0,4,2,7,9
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.900000,1,0,4,2,8,8
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.300000,1,0,4,4,9,8
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.900000,1,0,4,4,10,9
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.400000,0,0,3,3,11,10
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.600000,0,0,3,3,12,10
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.000000,0,0,3,3,13,11
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.980000,0,0,3,4,14,18
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.820000,0,0,3,4,15,19
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.420000,0,0,3,4,16,17
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,17.674828,1,1,4,1,17,8
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.520000,1,1,4,2,18,11
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.900000,1,1,4,1,19,14
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.010000,1,0,3,1,20,13
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.870000,0,0,3,2,21,16
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.300000,0,0,3,2,22,11
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.410000,0,0,3,4,23,10
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.050000,0,0,3,2,24,16
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,17.674828,1,1,4,1,25,9
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.700000,0,1,5,2,26,13
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.900000,1,1,5,2,27,12
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.500000,0,1,5,4,28,14
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.500000,0,1,5,6,29,12
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.600000,0,1,5,8,30,13
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.600000,1,1,4,2,31,10

In [ ]:
def sqr(x):
    return x*x




df['Sqr'] = df.carb.apply(sqr)

df

,Cars,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,new column,Length Car Names,Sqr
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.460000,0,1,4,4,0,9,16
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.020000,0,1,4,4,1,13,16
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.610000,1,1,4,1,2,10,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.440000,1,0,3,1,3,14,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.020000,0,0,3,2,4,17,4
5,Valiant,18.1,6,225.0,105,2.76,3.460,17.674828,1,0,3,1,5,7,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.840000,0,0,3,4,6,10,16
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.000000,1,0,4,2,7,9,4
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.900000,1,0,4,2,8,8,4
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.300000,1,0,4,4,9,8,16
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.900000,1,0,4,4,10,9,16
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.400000,0,0,3,3,11,10,9
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.600000,0,0,3,3,12,10,9
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.000000,0,0,3,3,13,11,9
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.980000,0,0,3,4,14,18,16
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.820000,0,0,3,4,15,19,16
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.420000,0,0,3,4,16,17,16
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,17.674828,1,1,4,1,17,8,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.520000,1,1,4,2,18,11,4
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.900000,1,1,4,1,19,14,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.010000,1,0,3,1,20,13,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.870000,0,0,3,2,21,16,4
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.300000,0,0,3,2,22,11,4
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.410000,0,0,3,4,23,10,16
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.050000,0,0,3,2,24,16,4
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,17.674828,1,1,4,1,25,9,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.700000,0,1,5,2,26,13,4
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.900000,1,1,5,2,27,12,4
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.500000,0,1,5,4,28,14,16
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.500000,0,1,5,6,29,12,36
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.600000,0,1,5,8,30,13,64
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.600000,1,1,4,2,31,10,4