<a href="https://colab.research.google.com/github/chandu01432/Upskill/blob/main/Visualization%20handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# agenda - Handson Practise for Visualization

In [ ]:
# Visualization

In [ ]:
# line plots - To understand the trends

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Diff between matlpotlib and seaborn

In [ ]:
# Matplotlib - Customisation(cooking maggie from scratch)
# Seaborn - readymade noodles

In [ ]:
# # Dataset link -> https://drive.google.com/file/d/18PV-dMn2y1KYCdZ0c9JoOnvEh4MIxeGy/view?usp=sharing

In [ ]:
df = pd.read_csv('/content/cars (1).csv')

In [ ]:
df

      mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand
0    14.0          8         350  165      4209          12  1972       US.
1    31.9          4          89   71      1925          14  1980   Europe.
2    17.0          8         302  140      3449          11  1971       US.
3    15.0          8         400  150      3761          10  1971       US.
4    30.5          4          98   63      2051          17  1978       US.
..    ...        ...         ...  ...       ...         ...   ...       ...
256  17.0          8         305  130      3840          15  1980       US.
257  36.1          4          91   60      1800          16  1979    Japan.
258  22.0          6         232  112      2835          15  1983       US.
259  18.0          6         232  100      3288          16  1972       US.
260  22.0          6         250  105      3353          15  1977       US.

[261 rows x 8 columns]

In [ ]:
df.shape

(261, 8)

In [ ]:
# print the head , tail , the information about the dataset , descriptive  statistical analysis of the dataset

In [ ]:
df.head()

    mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand
0  14.0          8         350  165      4209          12  1972       US.
1  31.9          4          89   71      1925          14  1980   Europe.
2  17.0          8         302  140      3449          11  1971       US.
3  15.0          8         400  150      3761          10  1971       US.
4  30.5          4          98   63      2051          17  1978       US.

In [ ]:
df.tail()

      mpg  cylinders cubicinches   hp weightlbs  time-to-60  year    brand
256  17.0          8         305  130      3840          15  1980      US.
257  36.1          4          91   60      1800          16  1979   Japan.
258  22.0          6         232  112      2835          15  1983      US.
259  18.0          6         232  100      3288          16  1972      US.
260  22.0          6         250  105      3353          15  1977      US.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   mpg          261 non-null    float64
 1   cylinders    261 non-null    int64
 2   cubicinches  261 non-null    object
 3   hp           261 non-null    int64
 4   weightlbs    261 non-null    object
 5   time-to-60   261 non-null    int64
 6   year         261 non-null    int64
 7   brand        261 non-null    object
dtypes: float64(1), int64(4), object(3)
memory usage: 16.4+ KB

In [ ]:
df.describe()

              mpg   cylinders          hp  time-to-60         year
count  261.000000  261.000000  261.000000  261.000000   261.000000
mean    23.144828    5.590038  106.360153   15.547893  1976.819923
std      7.823570    1.733310   40.499959    2.910625     3.637696
min     10.000000    3.000000   46.000000    8.000000  1971.000000
25%     16.900000    4.000000   75.000000   14.000000  1974.000000
50%     22.000000    6.000000   95.000000   16.000000  1977.000000
75%     28.800000    8.000000  138.000000   17.000000  1980.000000
max     46.600000    8.000000  230.000000   25.000000  1983.000000

In [ ]:
# check the null and duplicates  , handle those values
# null value - two options - drop it , fill it,  dropna() , fillna()

In [ ]:
# outliers - extreme values
# normal range - 5,10,15,20,35,50,6000
# median - 20 # Best option
# mean - nearly 3000  ,mean is very much affected by extreme values

In [ ]:
df.isnull().sum()

mpg            0
cylinders      0
cubicinches    0
hp             0
weightlbs      0
time-to-60     0
year           0
brand          0
dtype: int64

In [ ]:
df.isnull().values.any()  # True or False

np.False_

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'cubicinches', 'hp', 'weightlbs', 'time-to-60',
       'year', 'brand'],
      dtype='object')

In [ ]:
df1 = {
    'Name' : ["Sai", "Gopika",None, "Dravid"],
    'Age' : [26,None,38,60]
}
df2 = pd.DataFrame(df1)
df2

     Name   Age
0     Sai  26.0
1  Gopika   NaN
2    None  38.0
3  Dravid  60.0

In [ ]:
df2.isnull().sum()  # this will give you the count for each

Name    1
Age     1
dtype: int64

In [ ]:
df2.isnull().sum().sum()  # to get the total number of null values

np.int64(2)

In [ ]:
df3 = df2.dropna()  # drop the null values

In [ ]:
df3

     Name   Age
0     Sai  26.0
3  Dravid  60.0

In [ ]:
df2['Age'].fillna(df2['Age'].mean())

0    26.000000
1    41.333333
2    38.000000
3    60.000000
Name: Age, dtype: float64

In [ ]:
# value_counts()

In [ ]:
df

      mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand
0    14.0          8         350  165      4209          12  1972       US.
1    31.9          4          89   71      1925          14  1980   Europe.
2    17.0          8         302  140      3449          11  1971       US.
3    15.0          8         400  150      3761          10  1971       US.
4    30.5          4          98   63      2051          17  1978       US.
..    ...        ...         ...  ...       ...         ...   ...       ...
256  17.0          8         305  130      3840          15  1980       US.
257  36.1          4          91   60      1800          16  1979    Japan.
258  22.0          6         232  112      2835          15  1983       US.
259  18.0          6         232  100      3288          16  1972       US.
260  22.0          6         250  105      3353          15  1977       US.

[261 rows x 8 columns]

In [ ]:
df["brand"].value_counts()  # all the unique value counts

brand
US.        162
Japan.      51
Europe.     48
Name: count, dtype: int64

In [ ]:
# create a scatterplot between mpg and hp(x and y)
# make the plot  with respect to the 'brand' column,

In [ ]:
sns.scatterplot(data = df, x = "mpg", y = "hp")  # hue - explicitly differentiate between your values
plt.title("Scatter plot  of MPG VS HP")
plt.show()

NameError: name 'sns' is not defined

In [ ]:
# cylinders vs hp - scatterplot
# with respect to "brand"

In [ ]:
sns.scatterplot(data = df, x = "cylinders", y = "hp", hue = "brand")
plt.title("Scatter plot  of MPG VS HP")
plt.show()